version: '3'

tasks:
  build-go:
    cmds:
      - task -d targetted-back build
  lint-go:
    cmds:
      - task -d targetted-back lint
  test-go:
    cmds:
      - task -d targetted-back test

  lint-vue:
    cmds:
      - task -d targetted-client lint

  build:
    cmds:
      - docker-compose build
      - npm run build --prefix targetted-client/
  run:
    cmds:
      - docker-compose up -d
  stopb:
    cmds:
      - docker stop $(docker ps -a -q --filter="name=targetted-back") #TODO
  stop:
    cmds:
      - docker-compose stop
  ps:
    cmds:
      - docker ps
  r:
    cmds:
      - task stop
      - task build
      - task run
      - task ps

  run-dev-front:
    cmds:
      - docker-compose up targetted-back